// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkACJn6GAk80wGyiDMlQDr7B1iqxmuXyM',
    appId: '1:390479380583:web:71e8ccbbafc58276ce14c2',
    messagingSenderId: '390479380583',
    projectId: 'sorkhposhan-attendance',
    authDomain: 'sorkhposhan-attendance.firebaseapp.com',
    storageBucket: 'sorkhposhan-attendance.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOcTYriQr8Va5FLb-lzwRY-vdDol-jC7A',
    appId: '1:390479380583:android:16bd27c643bcd908ce14c2',
    messagingSenderId: '390479380583',
    projectId: 'sorkhposhan-attendance',
    storageBucket: 'sorkhposhan-attendance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMIdMngIVZa7KDyJCyfh-puN6LsC7WXhE',
    appId: '1:390479380583:ios:ca5b9cc98af4d2f5ce14c2',
    messagingSenderId: '390479380583',
    projectId: 'sorkhposhan-attendance',
    storageBucket: 'sorkhposhan-attendance.appspot.com',
    iosBundleId: 'com.example.sorkhposhan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMIdMngIVZa7KDyJCyfh-puN6LsC7WXhE',
    appId: '1:390479380583:ios:ca5b9cc98af4d2f5ce14c2',
    messagingSenderId: '390479380583',
    projectId: 'sorkhposhan-attendance',
    storageBucket: 'sorkhposhan-attendance.appspot.com',
    iosBundleId: 'com.example.sorkhposhan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkACJn6GAk80wGyiDMlQDr7B1iqxmuXyM',
    appId: '1:390479380583:web:21bc56a2f3519d71ce14c2',
    messagingSenderId: '390479380583',
    projectId: 'sorkhposhan-attendance',
    authDomain: 'sorkhposhan-attendance.firebaseapp.com',
    storageBucket: 'sorkhposhan-attendance.appspot.com',
  );
}
